---

adamalib:
  build: .
  ports:
    - "8888:8888"
  environment:
    PASSWORD: adamalib
    USE_HTTP: 1
  volumes:
    - .:/adamalib
    - notebooks:/data/local
    - /Users/wmoreira/TACC/adama:/data/adama
